version: '3.9'
services:
  post:
    container_name: frontend-product-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: frontend-product-dev
    restart: always
    volumes:
      - type: bind
        source: ./src
        target: /app/src
    ports:
      - 3000:8080
    env_file: .env


