version: '3.9'
services:
  post:
    container_name: frontend-product-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: frontend-product-prod
    ports:
      - 3000:80
    env_file: .env
